/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projet;

import java.util.Scanner;
import projet.Chifumi;

public class App {


    public static void main(String[] args) {
        Scanner scan = new Scanner(System.in);
        Chifumi classique = new Chifumi(3);

        char rejouer = 'O';

        while(rejouer == 'O') {
            classique.raz();
            while(classique.continuer()){
                System.out.println("Entrez un nombre pour jouer, 0 pour pierre, 1 pour feuille, 2 pour ciseaux.");
                int J1 = scan.nextInt();
                int J2 = (int)(Math.random() * 3);
                classique.jouerClassique(J1, J2 );
            }
            System.out.println("Souhaitez vous rejouer ? O pour confirmer");
            rejouer = scan.next().charAt(0);
        }

        scan.close();


    }
}
